#!/bin/bash
echo "快速修复BS2设备权限脚本"
echo "======================"
echo ""
echo "执行以下命令来修复权限（需要输入sudo密码）:"
echo ""
echo "1. sudo chmod 666 /dev/hidraw7"
echo "2. sudo udevadm control --reload-rules && sudo udevadm trigger"
echo "3. sudo usermod -aG plugdev $USER"
echo ""
echo "运行示例:"
echo "# 修复当前设备权限"
echo "sudo chmod 666 /dev/hidraw7"
echo ""
echo "# 重新加载udev规则"
echo "sudo udevadm control --reload-rules"
echo "sudo udevadm trigger"
echo ""
echo "# 将用户添加到plugdev组（可能需要）"
echo "sudo usermod -aG plugdev $USER"
echo ""
echo "# 验证修复（需要重新登录或重启）"
echo "ls -la /dev/hidraw7"
echo "groups $USER"
echo ""
echo "执行完后，需要:"
echo "1. 注销并重新登录（如果修改了用户组）"
echo "2. 或重启电脑"
echo "3. 然后重新运行测试脚本"